### PR TITLE
Removed unnecessary files and code from all source codes

### PR DESCRIPTION
**Pull request by xiuqiho**
Removed many of the redundant ".js" files, and unused ".html" files created during development. Huge chunks of commented code that were made during developments have also been removed.

### CODE REVIEW

**Review by george2000700 — APPROVED** [review]
verified changes made to files

**Review by thxcvanna — APPROVED** [review]
Approved. Thanks!

**Review by kahweiing — APPROVED** [review]
Approved!

**Review by cklee23 — APPROVED** [review]
Approved.

**Pull request merged**
