### PR TITLE
Merging completed "management/readme" feature into dev

### PR DESCRIPTION
**Pull request by xiuqiho**
Filled in UAT and Whitebox Testing Section
[UAT]
- Updated System State Diagram
- System Test Environment Preparation Instructions
- Full System Test Video

[Whitebox Testing]
- Highlighted "ChallengeManagement" class as selected class for demonstrating Whitebox testing
- Included test case names and descriptions of all test cases in "testsuite.py"
- Code Coverage Statistics sample images
- Execution instructions for test suite execution and code coverage stats generation (separated due to 'coverage' module's functionality)
- Full Whitebox Test Suite and Code Coverage execution video

### CODE REVIEW

**Review by thxcvanna — APPROVED** [review]
Approved.

**Review by kahweiing — APPROVED** [review]
Approved!

**Review by cklee23 — APPROVED** [review]
Approved

**Review by george2000700 — APPROVED** [review]
verified all changes in readme

**Pull request merged**
