### PR TITLE
Merging tentative WORKFLOW into main branch

### PR DESCRIPTION
**Pull request by xiuqiho**
- Tentative WORKFLOW merge into 'main' branch from 'dev'. 
- Non-CI items like ".zip" files are also removed

### CODE REVIEW

**Review by team-p4-5 — APPROVED** [review]
approved merge of 'dev' into 'main' for purpose of updating README content on 'main' branch

**Review by cklee23 — APPROVED** [review]
noted

**Review by thxcvanna — APPROVED** [review]
noted

**Review by kahweiing — APPROVED** [review]
Noted

**Pull request merged**
