### PR TITLE
Merging completed "UI/edit challenge settings" feature with back end into dev

### PR DESCRIPTION
**Pull request by george2000700**
completed edit_challenge_settings backend handling of editing challenges.

### CODE REVIEW

**Review by xiuqiho — APPROVED** [review]
Looks good, thanks!

**Review by thxcvanna — APPROVED** [review]
Approved. Good Job!

**Review by kahweiing — APPROVED** [review]
Approved

**Review by cklee23 — APPROVED** [review]
approved

**Pull request merged**
