### PR TITLE
Merging completed "register_player" feature into dev

### PR DESCRIPTION
**Pull request by thxcvanna**
New register page has been done by vanna, and backend handling of register logic and page routing completed for flask has been finalised.

### CODE REVIEW

**Review by kahweiing — APPROVED** [review]
Approved

**Review by xiuqiho — APPROVED** [review]
Thanks a lot for redesigning the register page! Looks good

**Review by cklee23 — APPROVED** [review]
Approved

**Review by george2000700 — APPROVED** [review]
Reviewed

**Pull request merged**
