### PR TITLE
ui/challenge

### PR DESCRIPTION
**Pull request by cklee23**
[ui/challenge]updated with new challenge features

### CODE REVIEW

**Review by kahweiing — APPROVED** [review]
Approved!

**Review by xiuqiho — APPROVED** [review]
approved, thanks for the work!

**Review by thxcvanna — APPROVED** [review]
Approved. Good Job!

**Review by george2000700 — APPROVED** [review]
reviewed, nice work

**Comment by cklee23** [comment]
[ADDED] new challenge features

**Pull request merged**
