### PR TITLE
Merging completed 'ui/leaderboard' feature into 'dev' branch

### PR DESCRIPTION
**Pull request by kahweiing**
Leaderboard logic is now synchronised with backend, can update and reflect challenge records in real time.

### CODE REVIEW

**Review by cklee23 — APPROVED** [review]
Approved.

**Review by xiuqiho — APPROVED** [review]
Thanks for the hard work! Looks good.

**Review by thxcvanna — APPROVED** [review]
Approved. Good job looks nice

**Review by george2000700 — APPROVED** [review]
Verified changes with the leaderboard.

**Pull request merged**
