### PR TITLE
Merging completed 'ui/instruction' feature into 'dev' branch

### PR DESCRIPTION
**Pull request by cklee23**
Instruction feature now has customised (and minimal) blockly command block choices, and has synchronised command issuing and command history logic in both front and backend

### CODE REVIEW

**Review by xiuqiho — APPROVED** [review]
Thanks for your help, approved!

**Review by kahweiing — APPROVED** [review]
Approved! Looks good

**Review by thxcvanna — APPROVED** [review]
Approved. good job!

**Review by george2000700 — APPROVED** [review]
Reviewed code,looks good

**Pull request merged**
