### PR TITLE
Merging completed backend data structure (Class) definitions into dev

### PR DESCRIPTION
**Pull request by xiuqiho**
Definitions include the Administrator, ChallengeSettings, Challenge and Student entity classes, as well as their respective 'management' control classes.

### CODE REVIEW

**Review by cklee23 — APPROVED** [review]
approved

**Review by kahweiing — APPROVED** [review]
Approved

**Review by thxcvanna — APPROVED** [review]
Approved

**Review by george2000700 — APPROVED** [review]
reviewed codes

**Pull request merged**
