### PR TITLE
Merge Completed Tooltip (ui/tooltip branch) to dev

### PR DESCRIPTION
**Pull request by thxcvanna**
Merge Tooltip in Control Dashboard to dev

### CODE REVIEW

**Review by xiuqiho — APPROVED** [review]
approved, thanks for completing the tooltip feature

**Review by cklee23 — APPROVED** [review]

**Review by cklee23 — APPROVED** [review]
approved

**Review by george2000700 — APPROVED** [review]
viewed and checked files

**Review by kahweiing — APPROVED** [review]
Approved. Nice work on the tooltip

**Pull request merged**
