### PR TITLE
Merge to add team's project .gitignore

### PR DESCRIPTION
**Pull request by xiuqiho**
Added team .gitignore file and removed .gitattributes from repo

### CODE REVIEW

**Review by team-p4-5 — DISMISSED** [review]
approved .gitignore

**Review by george2000700 — DISMISSED** [review]
reviewed

**Review by team-p4-5 — APPROVED** [review]
approved

**Review by george2000700 — APPROVED** [review]
reviewed

**Review by thxcvanna — APPROVED** [review]
noted

**Review by kahweiing — APPROVED** [review]
approved

**Review by cklee23 — COMMENTED** [review]
reviewed

**Review by cklee23 — COMMENTED** [review]
reviewed

**Pull request merged**
