### PR TITLE
Merging completed 'ui/virtual_map' feature into 'dev' branch

### PR DESCRIPTION
**Pull request by kahweiing**
Virtual map is now customised (and responsive) to reflect commands successfully executed by robotic car that users issued  using the blockly "instruction" feature.

### CODE REVIEW

**Review by cklee23 — APPROVED** [review]
Nice. Approved

**Review by thxcvanna — APPROVED** [review]
Approved. Looks nice thanks!

**Review by xiuqiho — APPROVED** [review]
Thanks for your help! Approved.

**Review by george2000700 — APPROVED** [review]
reviewed changes, good job

**Pull request merged**
