### PR TITLE
Merging completed 'ui/pairing' feature into 'dev' branch

### PR DESCRIPTION
**Pull request by cklee23**
Pairing logic is now synchronized with backend and can be done with car ID provided by web server instead of hard coded car IDs.

### CODE REVIEW

**Review by kahweiing — APPROVED** [review]
Approved

**Review by thxcvanna — APPROVED** [review]
Approved. Good Job!

**Review by xiuqiho — APPROVED** [review]
Looks good, thanks for the hard work!

**Review by george2000700 — APPROVED** [review]
reviewed changes made,, thank you for your work

**Pull request merged**
